### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by TimothyStephens** [nlapalu/SDDetector#5]
Hi,

I am encountering a segmentation fault when running SSDetector on my data (See error below).
My genome is 2.4Gbp and the blast.tab file is 7.3 Gigabytes. Is it possible that the size of my dataset is causing this error? 

Thanks,
Tim.

INFO:root:SQLite db stored in memory
INFO:root:Parsing alignments
INFO:root:Loading alignments into database
DEBUG:root:91215553 HSP parsed
INFO:root:Exporting matches after loading in database in gff3 format, file: sdd_0.9_3000_5000.gff3.loading
INFO:root:Removing self-self matches
INFO:root:Exporting matches after removing self-matches in gff3 format, file: sdd_0.9_3000_5000.gff3.selfmatch
INFO:root:Removing alignments below the identity threshold: 0.9
/var/spool/pbs/mom_priv/jobs/66335.flm1.SC: line 18:  4180 Segmentation fault      python ~/PROGRAMS/SDDetector/bin/segmental_duplication_detector.py blast.tab tab sdd_0.9_3000_5000.gff3 :memory: -g 3000 -l 5000 -a -v 3

**Comment by TimothyStephens** [comment]
Hi,

I reran on a different server and encountered the same problem but got a more informative error message. 

Traceback (most recent call last):
  File "/home/timothy.stephens/PROGRAMS/SDDetector/bin/segmental_duplication_detector.py", line 280, in <module>
    detector.runSDDetection()
  File "/home/timothy.stephens/PROGRAMS/SDDetector/bin/segmental_duplication_detector.py", line 73, in runSDDetection
    self.detectAndRemoveAlignmentBelowIdentityThreshold()
  File "/home/timothy.stephens/PROGRAMS/SDDetector/bin/segmental_duplication_detector.py", line 137, in detectAndRemoveAlignmentBelowIdentityThreshold
    self.db.deletelAlignments(lAlgmts)
  File "/home/timothy.stephens/PROGRAMS/SDDetector/lib/python2.7/site-packages/SDDetector/Db/AlignDB.py", line 69, in deletelAlignments
    .format(','.join(str(id) for id in lIds)))
MemoryError

I believed the problem is too many ids are being passed to the deletelAlignments function so I pre filtered the blast file. 
I believe the below command archives this. 
awk '($8/($4-$3+1))>=0.9' blast.tab > blast.filtered.tab

This appears to have fixed the problem and the program is now at the chaining alignments stage. Unfortunately at the rate it is progressing I don't thing it will finish in a feasible amount of time. 

Thanks,
Tim.
