### ISSUE TITLE
Identification of Long SDs

### ISSUE THREAD

**Issue by harish0201** [nlapalu/SDDetector#6]
Hi!

Thank you for developing the tool! I'm working on a vertebrate genome (2.5Gb) and I was trying to run this as this looked the easiest. I'm aware that you have not tested on such large genomes based on other issues.

I have both the soft-masked and hard-masked genome with REd (Hani Girgis).

We are interested in looking at long SDs, i.e greater than 10kb long. So, I had a few questions:

1. After finishing the blast and getting an XML, I'm running the "detector" portion of the pipeline for soft masked genome. Should I just increase the chain length to 10000, and the maximum gap to 5000? Would that make sense? What does your intuition suggest? Should I change the minimum match length (-t) or overlap (-p) to something else?
2. If I'm using the hard-filtered genome, should I use -db_hard_mask? and if so, what should the value for it?
3. There is some issue as to how the database is being used/called, as I keep getting this error consistently:
`Traceback (most recent call last):`
`File "/home/harish/miniconda3/envs/py2/bin/segmental_duplication_detector.py", line 408, in <module>
detector.runSDDetection()`
`File "/home/harish/miniconda3/envs/py2/bin/segmental_duplication_detector.py", line 110, in runSDDetection
self.chainAlignments(maxGap=self.maxGap, chainLength=self.chainLength)`
`File "/home/harish/miniconda3/envs/py2/bin/segmental_duplication_detector.py", line 237, in chainAlignments
cur.executescript(sql)`
`sqlite3.OperationalError: database is locked`

Any ideas why the above error pops up? My command is this: `segmental_duplication_detector.py P2.xml xml P2_0.9_5000_10000.gff3 :memory: -i 0.9 -g 5000 -l 10000 -a --procs 50`

Thank you!

**Comment by nlapalu** [comment]
Hi harish,
I haven't worked on the code of SDDetector for a long time...and it was clearly not optimised for large genomes. If you  increase the minimum size of alignment length (-t), you will remove small or very fragmented duplications, that's a good started point with large genome to detect very large SD.
For hard masking you have just to remove the -soft with maskFastaFromBed (Bedtools), you will have a hard masking with N. I don't think you will have to change the way I described the build of the DB, just change the -db_soft_mask  to -db_hard_mask  as you proposed. I think the associated algorithm is still 100. You can control it with blastdbcmd -db genome_masked -info
For the database locking, I suspect a "too many connections" issue, but not sure because you must have as many SQLIte DB as requested threads. 
If you agree to share your data, I can have a look to the problem.
Sorry for this delayed answer.
